### ISSUE TITLE
Unable to create replica set without sharing

### ISSUE THREAD

**Issue by milashenko** [awslabs/aws-quickstart#5]
Loop at line  https://github.com/awslabs/aws-quickstart/blob/master/mongodb/scripts/init.sh#L364 will never work without sharding, since at line https://github.com/awslabs/aws-quickstart/blob/master/mongodb/scripts/init.sh#L73, the MICROSHARDS is set to 0.

As the result, replica set will not be initialised.

**Comment by kdeggelman** [comment]
@milashenko - What are the symptoms of this issue? I just got the following error and am thinking it's because of this:

```16:55:55 UTC-0800	CREATE_FAILED	AWS::CloudFormation::WaitCondition	PrimaryReplicaNode0WaitForNodeInstallIO1	WaitCondition timed out. Received 0 conditions when expecting 1```

**Comment by tanmays** [comment]
I'm facing this issue as well. I get a "replica set not configured" error on running `printShardingStatus()` or `show dbs` after following the guide. Any updates on when this will be fixed?

**Comment by karthikkrishnanv** [comment]
@tamnays - The errors you mention are  because we haven't setup the replica nodes. The reference gets to a point of having the instances running Mongo - but you still need to initialize it. Please refer to https://docs.mongodb.org/manual/tutorial/deploy-replica-set/ on how to initialize the replica set. Use rs.initialize() on say PrimaryReplicaNode0 and use rs.add() on other replica nodes. Could you give it a try ?

**Comment by tanmays** [comment]
@karthikkrishnanv actually when I tried the template with sharding set to 2 everything is setup correctly. I will try your suggestion again without sharing with 3 replicate set, 0 clustershard, 0 microshards and get back to you. 

Another issue I saw with the template was that even when I explicitly choose EBS of type gp2, some volumes were created of type io1, this issue is problematic when I'm just trying it out and don't need provisioned iops and get charged for them. 

Here's a screenshot when I used template with 3 replicaset, 2 clustershards, 0 microshards with gp2 type EBS and it created some of type io1. https://dl.dropboxusercontent.com/u/5719952/AWS-Incorrect-VolumeTypes.png

Let me know if I'm mistaken or I should open this up as a separate issue.

**Comment by monsieurBelbo** [comment]
I had the same problem. The actual line is https://github.com/awslabs/aws-quickstart/blob/master/mongodb/scripts/init.sh#L392

```bash
while [ $c -lt ${MICROSHARDS} ]; do
    ...
done
```
Since `MICROSHARDS` could be set to 0 (if no sharding is intented) the replicaset is never initialized, and no error is thrown.

Also, the replicaset config only works for sharding, since the replicaset name is set in the config object will only work for sharded nodes.
